### ISSUE TITLE
Add 'Leaderboard' button next to 'Register Now' button.

### ISSUE THREAD

**Issue by dojutsu-user** [blurry-x-face/getsetfoss#111]
Add a "Leaderboard" button next to "Register Now" button. It should go to https://getsetfossleaderboard.pythonanywhere.com/leaderboard/

![Screenshot from 2019-11-10 14-09-05](https://user-images.githubusercontent.com/29149191/68541339-2eb04a00-03c4-11ea-9af1-ef1f836e63f0.png)

**Comment by sachin746** [comment]
i want to work on this

**Comment by dojutsu-user** [comment]
Assigned to @sachin746

**Comment by sachin746** [comment]
Sir I fork with the code and made a new branch and made changes to it to add leaderboard but now on compare and pull request it says can’t automatically merge
???????????
 

Sent from Mail for Windows 10

**Comment by dojutsu-user** [comment]
@sachin746 Please refer some good tutorials regarding making a pull request.

**Comment by yadavashu** [comment]
\\i want to do this

**Comment by dojutsu-user** [comment]
@yadavashu This issue is already assigned to @sachin746

**Comment by blank-27** [comment]
I want to claim this issue

**Comment by yk1ax** [comment]
@dojutsu-user I want to claim this issue

**Comment by the-rdt** [comment]
i want to claim the issue

**Comment by dojutsu-user** [comment]
Assigned to @yadavashu

**Comment by MightyMoin** [comment]
i want to claim this issue
