### ISSUE TITLE
Update the points criteria

### ISSUE THREAD

**Issue by dojutsu-user** [blurry-x-face/getsetfoss#112]
Update the points criteria here:

![Screenshot from 2019-11-10 14-14-15](https://user-images.githubusercontent.com/29149191/68541375-9070b400-03c4-11ea-86c2-89853b1b9efe.png)

New points criteria is as follows:

Extra: 5 points
Very Easy: 10 points
Easy: 15 points
Medium: 25 points
Hard: 30 points
Pro: 50 points
Codeburst: 100 points

**Comment by yk1ax** [comment]
I want to claim this

**Comment by dojutsu-user** [comment]
You cannot claim this.
You have already one issue assigned.
Please don't try to claim multiple issues at once.

**Comment by yk1ax** [comment]
My previously assigned issue is closed now. Can I claim it now ?

**Comment by dojutsu-user** [comment]
Assigned to @yk1ax

**Comment by blank-27** [comment]
I want to claim this issue

**Comment by dojutsu-user** [comment]
@blank-27 There is already an open PR for this issue.
