### ISSUE TITLE
Fix "Other Sponsors" Text

### ISSUE THREAD

**Issue by dojutsu-user** [blurry-x-face/getsetfoss#113]
"Other Sponsors" should be in the middle. Currently, it is slightly to the left.

![Screenshot from 2019-11-10 14-18-05](https://user-images.githubusercontent.com/29149191/68541407-11c84680-03c5-11ea-9bd9-25bcb626a9d7.png)

**Comment by yk1ax** [comment]
@dojutsu-user I want to claim this issue, I have created a PR for my previously assigned issue so I hope that won't be a problem

**Comment by blank-27** [comment]
@dojutsu-user I want to claim this issue

**Comment by dojutsu-user** [comment]
@yk1ax Since your other PR is not closed yet, I am assigning this issue to @blank-27

**Comment by blank-27** [comment]
fixed the "Other Sponsors" tag to center
