### ISSUE TITLE
Add Favicon to the website

### ISSUE THREAD

**Issue by dojutsu-user** [blurry-x-face/getsetfoss#114]
There is currently no favicon for the website. Add a favicon to the website. 
Favicon should be the logo of the Get Set FOSS.

![Screenshot from 2019-11-10 14-21-18](https://user-images.githubusercontent.com/29149191/68541446-8307f980-03c5-11ea-9e7b-4af571e25086.png)

**Comment by yk1ax** [comment]
I want to claim this

**Comment by dojutsu-user** [comment]
Assigned to @yk1ax 
Please make sure that you do a single PR with **correct PR title and description**.
