### ISSUE TITLE
Fix landing page image.

### ISSUE THREAD

**Issue by rishabhshuklax** [blurry-x-face/getsetfoss#7]
![](https://user-images.githubusercontent.com/42492389/68069676-65b1aa80-fd89-11e9-99c7-65f3fd91662b.png)

- [ ] Crop image from top to remove empty space.

**Comment by narendraiiitl** [comment]
![git](https://user-images.githubusercontent.com/54548515/68088263-3e3f0880-fe83-11e9-9986-d982105485ce.jpeg)

**Comment by dojutsu-user** [comment]
@narendraiiitl 
Please explain your comment.

**Comment by bajajvinamr** [comment]
I would want to work on this

**Comment by dojutsu-user** [comment]
You already have one issue assigned.
Please don't claim multiple issues.

**Comment by blank-27** [comment]
I m doing this issue

**Comment by rishabhshuklax** [comment]
Assigned to @blank-27

**Comment by blank-27** [comment]
Before--![firefox_BsBXJ1KkFt](https://user-images.githubusercontent.com/55805028/68153595-c8629c00-ff6b-11e9-8350-cbb9510524a4.png)
After--
![mPqUV29qoZ](https://user-images.githubusercontent.com/55805028/68153632-dadcd580-ff6b-11e9-863a-7343438309fa.png)
@dojutsu-user

**Comment by blank-27** [comment]
PR Name is --Branch 1.6(solved the issue #7) #64

**Comment by lav-joshi** [comment]
i want to do this

**Comment by yadavashu** [comment]
i want to do this

**Comment by dojutsu-user** [comment]
This is already assigned to @blank-27

**Comment by blank-27** [comment]
@dojutsu-user, the above uploaded screenshots are the changes done by me

**Comment by MightyMoin** [comment]
i want to do this

**Comment by sachin746** [comment]
i want to do this

**Comment by dojutsu-user** [comment]
This issue is solved.
I'm closing this.
